version: '3'

services:
  postgress:
    container_name: api_go_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: suporte
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - 5432:5432